# This checks all of a specific category of XML file. The category names are of the folders generated by xmlTypeSorter

usage="$(basename "$0") [-h] name -- Validate all files for a category in SortedXML against their schema

    name        Name of the category to check.
    -h          Show this help text"


if [[ $# -eq 0 ]] ; then
    echo "$usage"
    exit 0
fi

while getopts ":h" option; do
   case $option in
      h) # display Help
         echo "$usage"
         exit 0;;
   esac
done


xmllint  --noout --schema schemas/FS2019/$1.xsd utils/SortedXML/$1/*.xml 2>&1

exit 0

